---
title: "Week 2 Quiz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Who created Markdown?
  - **John Gruber**
  - Robert Gentleman
  - Yihui Xie
  - Hadley Wickham

2. When writing a document in R Markdown, how do you denote the beginning of an R code chunk?
  - `'''`
  - `<rcode>`
  - ` ```{r} `
  - `<code>`

3. When using knitr, how do you indicate the height and width of a plot created in a code chunk?
  - Set the 'size' and 'scale' options for the code chunk
  - Set the 'height' and 'width' options for the code chunk
  - Set the 'dpi' option for the code chunk
  - **Set the 'fig.height' and 'fig.width' options for the code chunk**

4. With some code chunks, we may not want the output generated by the chunk to be
rendered into HTML but would prefer to print the output verbatim. How can we specify
this preference for a given code chunk?
  - Set the option `highlight = TRUE`
  - Set the option `tidy = FALSE`
  - Set the option `message = FALSE`
  - **Set the option `results = "asis"`**

5. When using knitr and R Markdown and producing output in HTML, why should you never
edit the resulting HTML file?
  - Editing the HTML file requires knowledge of a separate markup language.
  - The HTML file is not a text file.
  - The Markdown file generated by knitr is the appropriate file to edit.
  - **Every time you knit() the R Markdown file, the HTML file will be overwritten**
