---
title: "Week 3 Quiz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Which of the following items is required for an R package to pass R CMD check without any warnings or errors?

  - a demo directory
  - example data sets
  - vignette
  - unit tests
  - **DESCRIPTION file**

2. Which of the following is a generic function in a fresh installation of R, with only the default packages loaded? (Select all that apply)

  - **predict**
  - **show**
  - dgamma
  - colSums
  - lm
  - **mean**

3. What function is used to obtain the function body for an S4 method function?

  - showMethods()
  - getClass()
  - **getMethod()**
  - getS3method()

4. Please download the R package [DDPQuiz3](https://d396qusza40orc.cloudfront.net/devdataprod/DDPQuiz3_1.0.zip) from the course web site. Examine the ğšŒğš›ğšğšŠğšğšğš–ğšğšŠğš— function implemented in the R/ sub-directory. What is the appropriate text to place above the ğšŒğš›ğšğšŠğšğšğš–ğšğšŠğš— function for Roxygen2 to create a complete help file?

  - **A**
    ```
    #' This function calculates the mean
    #'
    #' @param x is a numeric vector
    #' @return the mean of x
    #' @export
    #' @examples
    #' x <- 1:10
    #' createmean(y)
    ```

  - B
    ```
    #' This function calculates the mean
    #'
    #' @return the mean of x
    #' @export
    #' @examples
    #' x <- 1:10
    #' createmean(x)
    ```
    
  - C
    ```
    #' This function calculates the mean
    #' 
    #' @param x is a numeric vector
    #' @return the mean of x
    #' @export
    #' @examples 
    #' x <- 1:10
    #' createmean(x)
    ```
    
  - D
    ```
    This function calculates the mean
    @param x is a numeric vector
    @return the mean of x
    @export
    @examples
    x <- 1:10
    createmean(x)
    ```