---
title: "Week 1 Quiz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Which of the following is a principle of analytic graphics?
  - Only do what your tools allow you to do
  - **Describe and document the evidence**
  - Make judicious use of color in your scatterplots
  - Don't plot more than two variables at at time
  - Show box plots (univariate summaries)

2. What is the role of exploratory graphs in data analysis?
  - They are used in place of formal modeling.
  - **The goal is for personal understanding.**
  - Only a few are constructed.
  - Axes, legends, and other details are clean and exactly detailed.

3. Which of the following is true about the base plotting system?
  - Margins and spacings are adjusted automatically depending on the type of plot and the data
  - The system is most useful for conditioning plots
  - **Plots are created and annotated with separate functions**
  - Plots are typically created with a single function call

4. Which of the following is an example of a valid graphics device in R?
  - A file folder
  - The keyboard
  - **A PDF file**
  - A socket connection

5. Which of the following is an example of a vector graphics device in R?
  - PNG
  - TIFF
  - GIF
  - JPEG
  - **SVG**

6. Bitmapped file formats can be most useful for
  - Plots that require animation or interactivity
  - Plots that are not scaled to a specific resolution
  - Plots that may need to be resized
  - **Scatterplots with many many points**

7. Which of the following functions is typically used to add elements to a plot in the base
graphics system?
  - `plot()`
  - **`text()`**
  - `hist()`
  - `boxplot()`

8. Which function opens the screen graphics device on Windows?
  - `jpeg()`
  - `xfig()`
  - `postscript()`
  - **`windows()`**

9. What does the `pch` option to `par()` control?
  - **the plotting symbol/character in the base graphics system**
  - the orientation of the axis labels on the plot
  - the size of the plotting symbol in a scatterplot
  - the line width in the base graphics system
  
10. If I want to save a plot to a PDF file, which of the following is a correct way of doing that?
  - **Construct the plot on the screen device and then copy it to a PDF file with `dev.copy2pdf()`**
  - Construct the plot on the PNG device with png(), then copy it to a PDF with `dev.copy2pdf()`.
  - Open the PostScript device with `postscript()`, construct the plot, then close the device with `dev.off()`.
  - Open the screen device with `quartz()`, construct the plot, and then close the device with `dev.off()`.
